### ISSUE TITLE
Seed errors when Batch Count > 1

### ISSUE THREAD

**Issue by gerikhan** [ThereforeGames/unprompted#194]
### Due diligence

- [X] I checked for similar issues and couldn't find any.
- [X] My WebUI and Unprompted are both up-to-date.
- [X] I disabled my other extensions but the problem persists.

### Describe the bug

When running with a Batch Count greater than 1, an error appears in the log and unprompted's seed does not change for the next image. It's a new main seed, so different pictures, but unprompted's seed is the same and produces the shame Choose results.

This does NOT occur with Batch **Size** > 1. Just Batch **Count** > 1. A workaround, but not a great one.

This has been consistent since I upgraded Automatic1111 to 1.6.0 and unprompted to 9.15.2. Python is 3.10.6. I did not install over my previous version of automatic1111, it's a fresh folder.

I have tried what I can to fix this, including uninstalling unprompted, deleting venv and reinstalling. The only extensions I have are the built-in ones, plus unprompted. Installed unprompted via the extensions tab.

### Prompt

[call test]

test.txt > portrait of a [choose]man|woman[/choose]

when ran with a batch count of 10, produces 10 men or 10 women, but it used to randomly switch.

### Log output

```shell
*** Error running process_batch: C:\StableDiffusion\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py]
    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 737, in process_batch
        if "extra_network_data" in p: extra_networks.deactivate(p, p.extra_network_data)
    TypeError: argument of type 'StableDiffusionProcessingTxt2Img' is not iterable

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 643, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "C:\StableDiffusion\stable-diffusion-webui\extensions\unprompted\scripts\unprompted.py", line 739, in process_batch
        self.log.exception("Exception while deactiating extra networks")
    AttributeError: 'Scripts' object has no attribute 'log'
```

### Unprompted version

9.15.2

### WebUI version

1.6.0

### Other comments

This has been a really fun and useful extension to work with! Great for generating lots of varied shots of the same character in a controlled way. Thanks for the hard work.

**Comment by ThereforeGames** [comment]
Hi @gerikhan,

Thank you for the detailed report! I have just released Unprompted v9.16.0 with a couple fixes for `batch_count` > 1. Feel free to try it out and let me know if it gives you any further touble. Thanks.
